services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/var/www/html
    depends_on:
      oracle:
        condition: service_healthy

  oracle:
    image: adordm/oracle-database-enterprise:12.2.0.1-slim
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=oracle
      - ORACLE_CHARACTERSET=AL32UTF8
      - ORACLE_ALLOW_REMOTE=true
  # https://medium.com/xp-inc/dica-r%C3%A1pida-criando-base-de-dados-oracle-vers%C3%A3o-21-3-0-no-docker-357b05754b84

#   db:
#     image: mysql:5.7
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: laravel
#       MYSQL_USER: laravel
#       MYSQL_PASSWORD: secret
#     ports:
#       - "3306:3306"
#     volumes:
#       - db_data:/var/lib/mysql
#     healthcheck:
#       test: ["CMD-SHELL", "mysqladmin ping -uroot -p$${MYSQL_ROOT_PASSWORD} -h 127.0.0.1 --silent"]
#       interval: 10s
#       timeout: 5s
#       retries: 10

# volumes:
#   db_data:
